### PR TITLE
Update to 98.0.4758.102

### PR DESCRIPTION
**Pull request by Zoraver**
Hexavalent 98.0.4758.102 compiled and is running well on Fedora. No major changes to the patches were required.

### CODE REVIEW

**Comment by qua3k** [comment]
We should rebase on 82 first to keep a linear history.

**Comment by flawedworld** [comment]
@Zoraver Please rebase this

**Comment by flawedworld** [comment]
Changes from dev should be incorporated and altered to follow our history.

**Comment by flawedworld** [comment]
Didn't mean to close

**Pull request merged**
