### PR TITLE
Hexavalent helper script (experimental)

### PR DESCRIPTION
**Pull request by loryeam**
Hexavalent helper script currently has support for:
* applying patches based on target OS,
* copying gn args to build directory,
* applying hexavalent branding.

In future, direct access of 'config' dictionary should be replaced with appropriate functions and config should probably be moved to a separate file.

### CODE REVIEW

**Comment by loryeam** [comment]
This pull request addresses #25 and #49 (only on Windows for now since I don't have a Linux machine).

**Comment by flawedworld** [comment]
Having had a brief look, this seems good, I need to fully review the python code once I get a bit more time. We may potentially move the python script to it's own repo so it can be worked on a bit easier

**Comment by flawedworld** [comment]
@loryeam Licencing for all branding and icons must be explicitly stated. It's not under BSD licencing and is all rights reserved.

**Comment by loryeam** [comment]
We can put the script and icons in a private repo with different licencing.

**Pull request closed without merging**
