### PR TITLE
Update to 99.0.4844.51

### PR DESCRIPTION
**Pull request by Zoraver**
Notes:
* As quh4gko8 observed in https://github.com/GrapheneOS/Vanadium/pull/159, `0011-disable-prefetching-suggested-pages-by-default.patch` no longer applies, since `OfflinePagesPrefetching` is now disabled by default.
* Upstream refactored `chrome/browser/resources/settings/BUILD.gn` in https://github.com/chromium/chromium/commit/3387ae90c5131ed9ef4b6a46e509db8e71b0a043 and `0037-Add-WebRTC-policy-toggle-to-settings.patch` was updated to take this into account.
* `windows/0002-Add-VS-2022-support.patch` is no longer needed as upstream now appears to support VS 2022.

I will let you know once I have a successful build.

### CODE REVIEW

**Comment by flawedworld** [comment]
Please make sure to update the Linux txt also as this version targets all desktop platforms

**Comment by qua3k** [comment]
The kServiceWithJit sandbox type is a thing as of https://github.com/chromium/chromium/commit/7242135038466f907211a7b943ba8d697a335fd4; we need to exempt those processes.

**Comment by Zoraver** [comment]
Hexavalent 99.0.4844.51 compiled and seems to be running well on Fedora. My most recent commit should exempt `kServiceWithJit` from having dynamic code generation be disabled; please review it carefully.

**Comment by qua3k** [comment]
Looks good 👍

**Review by qua3k — APPROVED** [review]

**Comment by flawedworld** [comment]
Needs rebase, seems ok to me.

**Pull request merged**
