### PR TITLE
Disable Credit Card autofill

### PR DESCRIPTION
**Pull request by Douloureux**

### CODE REVIEW

**Comment by flawedworld** [comment]
I'm not sure all of this functionality is possible outside of Google Chrome.

**Comment by Douloureux** [comment]
image
Fake card

**Comment by e-zk** [comment]
I'm curious what the reasoning is for wanting to disable this by default.   
Is it because it makes it too easy for a phishing / malicious website to trick a user into giving their card info through the autofill?

**Comment by Douloureux** [comment]
Yes, and on Windows at least, it fills it out without any checks, so a person other than the actual owner could be able to use it maliciously. I don't know how this works on other platforms.

**Comment by qua3k** [comment]
> Yes, and on Windows at least, it fills it out without any checks, so a person other than the actual owner could be able to use it maliciously. I don't know how this works on other platforms.

This isn’t a concern. Local attacks are largely out of scope; an attacker that has that level of access can cause far more damage than racking up charges on your credit card.

**Pull request closed without merging**
