### PR TITLE
update to 100.0.4896.46

### PR DESCRIPTION
**Pull request by loryeam**
Builds on:
* [ ] linux
* [x] windows (with errors)

Tested on:
* [ ] linux
* [x] windows

### CODE REVIEW

**Comment by loryeam** [comment]
There are some errors when building this on Windows, looks like an upstream issue. However, it seems to work fine.
```
[38919/39244] ACTION //tools/v8_context_snapshot:generate_v8_context_snapshot(//build/toolchain/win:win_clang_x64)
[0317/171227.290:ERROR:histogram.cc(445)] Histogram: V8.GC.Cycle.CollectionRate.Full.Cpp has bad minimum: 0
```

**Comment by loryeam** [comment]
The issue is fixed in upstream in newer versions of chromium: https://chromium.googlesource.com/chromium/src/third_party/+/db9f65f918a051f08fb616f296f4208c88474d40

**Comment by flawedworld** [comment]
If they end up using this tag for stable, we can cherry-pick that commit.

**Comment by loryeam** [comment]
Chrome beta is now at 100.0.4896.56.

**Comment by loryeam** [comment]
Replaced by #114.

**Pull request closed without merging**
