### PR TITLE
Build with full LTO and enable process isolated sandboxed iframes

### PR DESCRIPTION
**Pull request by Zanthed**
Solves https://github.com/Hexavalent-Browser/Hexavalent/issues/72 and https://github.com/Hexavalent-Browser/Hexavalent/issues/102

The current behaviour for sandboxed iframes (the HTML attribute `sandbox` for `iframe`) and all other iframes are that they run in the same process as mentioned in the comments here: https://source.chromium.org/chromium/chromium/src/+/main:content/public/common/content_features.cc;l=449-454?q=IsolateSandboxedIframes&ss=chromium%2Fchromium%2Fsrc

This will allow iframes with the `sandbox` attribute to run in separate processes now. The behaviour for non-`sandbox` iframes is unchanged.

Relevant discussion about site isolation and iframes: https://bugs.chromium.org/p/chromium/issues/detail?id=510122

### CODE REVIEW

**Review by flawedworld — APPROVED** [review]

**Comment by Zoraver** [comment]
Just curious, what were your build times before and after `patches/0041-build-with-full-LTO.patch` was applied?

**Comment by Zanthed** [comment]
image

**Comment by Zanthed** [comment]
tbh I didn't measure it but this build machine we have has 128GB of memory and I needed a swapfile to prevent it from being killed by OOM Killer.

it never actually reached 128GB, but it did reach 98GB and the swapfile was used a bit so it wouldn't be killed.

I can try doing a full fresh build and see what happens. But I believe it's around 2-3 hours with 32 cores of an AMD Ryzen 9 3900X.

**Comment by Zanthed** [comment]
If in the event it does get killed, you can just re-run the same ninja build command and it will pick up where it left off and build successfully.

This does mean there can be some tweaking done in the OS you're on to prevent it from being killed so aggressively like Linux kernel options.

**Comment by Douloureux** [comment]
> Just curious, what were your build times before and after `patches/0041-build-with-full-LTO.patch` was applied?

Not much change in build times, just linking takes a bit longer, and uses a lot more RAM.

**Pull request closed without merging**
